name: WBGT Mail Sender

on:
  schedule:
    - cron: "*/5 * * * *"     # 每 5 分钟（UTC）
  workflow_dispatch:          # 保留手动触发

jobs:
  send:
    runs-on: ubuntu-latest
    concurrency:
      group: wbgt-mail
      cancel-in-progress: true   # 上一轮没结束就取消，避免重叠
    timeout-minutes: 5           # 整个作业最长 5 分钟
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # ✅ API 预检：能拿到 JSON 的开头再继续，避免无意义发信重试
      - name: Precheck API reachability
        run: |
          set -e
          echo "Checking API..."
          curl -sS -H "User-Agent: Mozilla/5.0" \
            "https://get-wbgt.onrender.com/extract_all?url=https://www.wbgt.env.go.jp/graph_ref_td.php%3Fregion=10%26prefecture=82%26point=82056" \
            | head -c 400

      # ✅ 运行发送脚本；脚本内部自带 3 次重试（见第2步）
      - name: Run mail script (script has internal retry)
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 3     # 单次最多 3 分钟
          max_attempts: 1        # 外层不再多次重试，交给脚本内部
          retry_on: error
          command: python send_json_mail.py
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          TO_ADDR:   ${{ secrets.TO_ADDR }}
